apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsc-ts-api-app
  namespace: jsc-ns
  labels:
    app: jsc-ts-api-app
    component: jsc-ts-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsc-ts-api-app
      tier: frontend
  template:
    metadata:
      labels:
        app: jsc-ts-api-app
        tier: frontend
    spec:
      containers:
        - name: jsc-ts-api
          image: jscdroiddev/jsc-ts-api:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Asia/Bangkok"
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
            - name: APP_NAME
              value: "Generate image using ComfyUI"
            - name: APP_DESCRIPTION
              value: "Simple API to run a ComfyUI workflow and generate an image."
            - name: APP_VERSION
              value: "v0.0.1"
            - name: COMFYUI_URL
              value: "http://comfyui-server:8188/"
          ports:
            - containerPort: 3000
              name: jsc-ts-api-app
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "500m"
              memory: "128Mi"
